// lib/learn/schema.ts — GENERATED by scripts/generate-sql-seed.mjs. Do not edit by hand.
// Column/type/row-count metadata for the 08/ SQL and 09/ Python dataset's four
// tables — drives the interactive schema-popover chips in
// components/learn/table-chips.tsx (hover/click a table name in an exercise
// card to see its columns and row count). Derived from the same CREATE TABLE
// columns and row arrays as sql-seed.ts / python-data.ts; adds zero PRNG
// calls, so those two files stay byte-identical whether or not this runs.

export type SchemaColumnType = 'integer' | 'text' | 'real' | 'date' | 'datetime'

export interface SchemaColumn {
  name: string
  type: SchemaColumnType
}

export interface TableSchema {
  name: string
  rows: number
  columns: SchemaColumn[]
}

export const TABLE_SCHEMAS: Record<string, TableSchema> = {
  patients: {
    name: 'patients',
    rows: 50,
    columns: [
      { name: 'patient_id', type: 'integer' },
      { name: 'name', type: 'text' },
      { name: 'sex', type: 'text' },
      { name: 'birth_date', type: 'date' },
      { name: 'city', type: 'text' },
    ],
  },
  encounters: {
    name: 'encounters',
    rows: 188,
    columns: [
      { name: 'encounter_id', type: 'integer' },
      { name: 'patient_id', type: 'integer' },
      { name: 'dept', type: 'text' },
      { name: 'admit_date', type: 'date' },
      { name: 'discharge_date', type: 'date' },
    ],
  },
  labs: {
    name: 'labs',
    rows: 558,
    columns: [
      { name: 'lab_id', type: 'integer' },
      { name: 'encounter_id', type: 'integer' },
      { name: 'test_name', type: 'text' },
      { name: 'value', type: 'real' },
      { name: 'unit', type: 'text' },
      { name: 'taken_at', type: 'datetime' },
    ],
  },
  medications: {
    name: 'medications',
    rows: 120,
    columns: [
      { name: 'med_id', type: 'integer' },
      { name: 'patient_id', type: 'integer' },
      { name: 'drug_name', type: 'text' },
      { name: 'start_date', type: 'date' },
      { name: 'end_date', type: 'date' },
    ],
  },
}
