// scripts/word-themes.mjs
// The 8 curated theme word lists shared by every word game's generator
// (word search, word scramble). Order and content are load-bearing: the
// word-search generator's PRNG stream walks these arrays, so ANY change
// here changes that committed bank. Edit only with a deliberate regenerate.
export const THEMES = [
  { name: 'In the Kitchen', words: ['SPATULA','WHISK','KETTLE','SKILLET','LADLE','GRATER','TOASTER','BLENDER','OVEN','APRON','RECIPE','SPICES','TIMER','MIXER','TONGS','PANTRY','GRIDDLE','COLANDER','PITCHER','PLATTER','NAPKIN','SAUCER','TEAPOT','BURNER','FREEZER','CUTLERY','PEELER','JUICER'] },
  { name: 'Garden', words: ['TULIP','DAISY','ROSES','SOIL','SHOVEL','TROWEL','MULCH','SEEDS','BLOOM','PETAL','HEDGE','VINES','CLOVER','ORCHID','PANSY','FERNS','ROOTS','SPROUT','GARDENIA','LILAC','PEONY','THORN','POLLEN','NECTAR','TRELLIS','COMPOST','PLANTER','PRUNING'] },
  { name: 'Weather', words: ['BREEZE','CLOUDY','THUNDER','DRIZZLE','RAINBOW','SUNSHINE','FROST','HUMID','STORMY','WINDY','HAIL','FOGGY','CHILLY','MONSOON','TORNADO','BLIZZARD','DEWDROP','ICICLE','PUDDLE','UMBRELLA','FORECAST','SEASONS','AUTUMN','SPRING','WINTER','SUMMER','MISTY','GUSTY'] },
  { name: 'Travel', words: ['PASSPORT','SUITCASE','AIRPORT','JOURNEY','VOYAGE','HOTEL','RESORT','BEACH','CRUISE','TICKET','LUGGAGE','CAMERA','POSTCARD','SOUVENIR','ISLAND','SAFARI','TOURIST','COMPASS','ATLAS','HIGHWAY','TRAIN','SUBWAY','HARBOR','VILLAGE','CASTLE','MUSEUM','MARKET','SUNSET'] },
  { name: 'Animals', words: ['GIRAFFE','ELEPHANT','PENGUIN','DOLPHIN','RACCOON','SQUIRREL','LEOPARD','OSTRICH','PEACOCK','HAMSTER','RABBIT','TURTLE','MONKEY','PARROT','DONKEY','BEAVER','BADGER','WALRUS','JAGUAR','GAZELLE','HEDGEHOG','OTTER','PANDA','KOALA','ZEBRA','MOOSE','BISON','CAMEL'] },
  { name: 'Music', words: ['MELODY','RHYTHM','GUITAR','TRUMPET','VIOLIN','CLARINET','HARMONY','CHORUS','SOPRANO','BALLAD','CONCERT','PIANIST','DRUMMER','WHISTLE','LULLABY','ENCORE','TEMPO','OPERA','BANJO','CELLO','FLUTE','ORGAN','PIANO','SINGER','POLKA','WALTZ','JAZZ','MAESTRO'] },
  { name: 'Baking', words: ['FLOUR','SUGAR','YEAST','DOUGH','ICING','GLAZE','MUFFIN','COOKIE','BROWNIE','CUPCAKE','FROSTING','SPRINKLE','CINNAMON','VANILLA','CARAMEL','PASTRY','STRUDEL','BISCUIT','PRETZEL','CRUST','BATTER','RAISIN','WALNUT','ALMOND','HONEY','COCOA','SCONE','OATMEAL'] },
  { name: 'Around Town', words: ['LIBRARY','BAKERY','MARKET','THEATER','MUSEUM','STATION','AVENUE','PLAZA','CORNER','BRIDGE','FOUNTAIN','SIDEWALK','TRAFFIC','PARADE','FESTIVAL','DINER','FLORIST','BARBER','TAILOR','GROCERY','PHARMACY','SCHOOL','CHAPEL','GAZEBO','BENCH','LANTERN','TROLLEY','MAILBOX'] },
]
